require('dotenv').config();
const nodemailer = require('nodemailer');
const xlsx = require('xlsx');
const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
  batchSize: 100,
  delayMs: 45000, // 45 seconds between each email
  excelFile: 'HR_Email_Automation.xlsx', // Your specified Excel file
  progressFile: 'progress.json',
  resumePath: path.join(__dirname, 'Twaran_Gupta_Backend_Software_Engineer.pdf'), // Your specified PDF
  // Test mode: run with `TEST_MODE=true node mailer.js` to send ONE email to
  // testEmail and exit, without reading the list or touching progress.json.
  testMode: process.env.TEST_MODE === 'true',
  testEmail: 'twarangupta01@gmail.com',
};

// Subject lines are rotated per contact so a few hundred identical subjects
// do not look like a bulk blast to spam filters. Add or edit freely.
const SUBJECTS = [
  'Application: Software Engineer (2 years experience) - Twaran Gupta',
  'Software Engineer - improved API response times by 60% at ZS Associates - Twaran Gupta',
  'Backend / Full-Stack Engineer open to new roles - Twaran Gupta',
  'Node.js / React Developer (2 yrs) looking to join your team - Twaran Gupta',
  'Software Engineer who loves building products - Twaran Gupta',
  'Experienced Software Engineer exploring opportunities - resume attached - Twaran Gupta',
  'Full-Stack Software Engineer application - Twaran Gupta',
];

// Setup Nodemailer transport using your environment variables
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASS,
  },
});

// Helper to track progress
function getProgress() {
  if (!fs.existsSync(CONFIG.progressFile)) {
    return { lastIndex: 0 };
  }
  return JSON.parse(fs.readFileSync(CONFIG.progressFile, 'utf8'));
}

function saveProgress(lastIndex) {
  fs.writeFileSync(CONFIG.progressFile, JSON.stringify({ lastIndex }, null, 2));
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Plaintext version. Sent alongside the HTML as multipart/alternative:
// improves inbox placement and gives a fallback for clients that strip HTML.
function buildTextBody(hrName) {
  return `Hi ${hrName},

This email was not generated by AI. I am reaching out personally because I love programming and I am a Builder by heart. It is the one thing I have always kept coming back to; I do not really have other hobbies, and I genuinely enjoy spending my time learning, solving problems, and creating things.

I left my last job at ZS Associates for family reasons. Things are in a better place now, and I am ready to get back into the game and find a team where I can contribute as a backend or full-stack engineer.

At ZS Associates, I built and shipped backend services for Pfizer and Merck, including multi-tenant REST APIs secured with JWT and role-based access. I also helped re-architect services asynchronously with Redis caching, which improved production API response times by 60% (from about 500ms to 200ms). Outside of work, I designed and shipped SinkedIn, a live full-stack platform, end to end.

I am available to start immediately, and open to remote roles or on-site in Pune, Bangalore, Hyderabad, or Delhi NCR.

Core Tech Stack
Backend: Node.js, Express.js, PostgreSQL, Redis, REST APIs
Frontend: React.js, Next.js
Cloud & Tools: AWS, Docker, Git, CI/CD

Even a quick note on whether your team is hiring backend or full-stack engineers would help. My resume is attached for your review.

Twaran Gupta
+91 9718117060
linkedin.com/in/twarangupta | github.com/twarangupta | twarangupta.com`;
}

// HTML version. Plain formatting, tech stack bolded.
function buildHtmlBody(hrName) {
  return `
  <div>
    <p>Hi ${hrName},</p>

    <p>This email was not generated by AI. <strong>I am reaching out personally</strong> because I love programming and I am a Builder by heart. It is the one thing I have always kept coming back to; I do not really have other hobbies, and I genuinely enjoy spending my time learning, solving problems, and creating things.</p>

    <p>I left my last job at ZS Associates for family reasons. Things are in a better place now, and I am ready to get back into the game and find a team where I can contribute as a backend or full-stack engineer.</p>

    <p>At ZS Associates, I built and shipped backend services for Pfizer and Merck, including multi-tenant REST APIs secured with JWT and role-based access. I also helped re-architect services asynchronously with Redis caching, which improved production API response times by 60% (from about 500ms to 200ms). Outside of work, I designed and shipped SinkedIn, a live full-stack platform, end to end.</p>

    <p>I am available to start immediately, and open to remote roles or on-site in Pune, Bangalore, Hyderabad, or Delhi NCR.</p>

    <p>
      Core Tech Stack<br>
      Backend: <strong>Node.js, Express.js, PostgreSQL, Redis, REST APIs</strong><br>
      Frontend: <strong>React.js, Next.js</strong><br>
      Cloud &amp; Tools: <strong>AWS, Docker, Git, CI/CD</strong>
    </p>

    <p>Even a quick note on whether your team is hiring backend or full-stack engineers would help. My resume is attached for your review.</p>

    <p>
      Twaran Gupta<br>
      +91 9718117060<br>
      <a href="https://www.linkedin.com/in/twarangupta">LinkedIn</a> | <a href="https://github.com/twarangupta">GitHub</a> | <a href="https://twarangupta.com">Portfolio</a>
    </p>
  </div>
  `;
}

async function sendTestEmail() {
  const hrName = 'Hiring Team';
  const mailOptions = {
    from: `"Twaran Gupta" <${process.env.GMAIL_USER}>`,
    replyTo: 'twarangupta01@gmail.com',
    to: CONFIG.testEmail,
    subject: `[TEST] ${SUBJECTS[0]}`,
    text: buildTextBody(hrName),
    html: buildHtmlBody(hrName),
    attachments: [
      {
        filename: 'Twaran_Gupta_Backend_Software_Engineer.pdf',
        path: CONFIG.resumePath,
      },
    ],
  };
  await transporter.sendMail(mailOptions);
  console.log(`Test email sent to ${CONFIG.testEmail}. Check how it renders, then run without TEST_MODE to send real batches.`);
}

async function runMailer() {
  // Read the Excel file
  const workbook = xlsx.readFile(CONFIG.excelFile);
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const contacts = xlsx.utils.sheet_to_json(sheet);

  // Get current batch
  const { lastIndex } = getProgress();
  const batch = contacts.slice(lastIndex, lastIndex + CONFIG.batchSize);

  if (batch.length === 0) {
    console.log('All contacts have been processed!');
    return;
  }

  console.log(`Starting batch from index ${lastIndex} to ${lastIndex + batch.length}...`);

  // Process each contact in the batch
  for (let i = 0; i < batch.length; i++) {
    const contact = batch[i];
    const absoluteIndex = lastIndex + i;

    // Data mapping from your cleaned columns
    const firstName = contact['First Name'] ? String(contact['First Name']).trim() : '';
    let hrName = firstName;
    if (!hrName) hrName = 'Hiring Team';

    const hrEmail = contact['Email'];

    // Safeguard: skip blank emails (list is already verified)
    if (!hrEmail) {
      console.log(`Skipping index ${absoluteIndex}: No email found.`);
      continue;
    }

    // Rotate the subject line based on the contact's absolute position
    const subject = SUBJECTS[absoluteIndex % SUBJECTS.length];

    // Email options: send both plaintext and HTML (multipart/alternative)
    const mailOptions = {
      from: `"Twaran Gupta" <${process.env.GMAIL_USER}>`,
      replyTo: 'twarangupta01@gmail.com', // Ensures replies go to your main inbox
      to: hrEmail,
      subject: subject,
      text: buildTextBody(hrName),
      html: buildHtmlBody(hrName),
      attachments: [
        {
          filename: 'Twaran_Gupta_Backend_Software_Engineer.pdf',
          path: CONFIG.resumePath,
        },
      ],
    };

    // Send Email
    try {
      await transporter.sendMail(mailOptions);
      console.log(`[${i + 1}/${batch.length}] Sent to ${hrEmail}`);
    } catch (err) {
      console.error(`Failed sending to ${hrEmail}:`, err.message);
    }

    // Delay between emails to protect sender reputation. Runs whether the
    // send succeeded or failed, so a burst of failures cannot hammer Gmail
    // with no spacing. Skips the delay after the last email in the batch.
    if (i < batch.length - 1) {
      await sleep(CONFIG.delayMs);
    }
  }

  // Update tracking file
  saveProgress(lastIndex + batch.length);
  console.log(`Batch complete. Progress updated to index ${lastIndex + batch.length}.`);
}

if (CONFIG.testMode) {
  sendTestEmail().catch(console.error);
} else {
  runMailer().catch(console.error);
}